### ISSUE TITLE
[Request] Multiple recordId traversal

### ISSUE THREAD

**Issue by crossknight** [nogdb/libnogdb#13]
Cannot use sql for traverse many rids
e.g.
traverse out() from [#1:1,#1:2]
because
nogdb::ResultSetCursor outEdgeBfsCursor(const nogdb::Txn&                 txn,
                                       const nogdb::RecordDescriptor&    recordDescriptor,
                                       const unsigned int                minDepth,
                                       const unsigned int                maxDepth,
                                       const nogdb::PathFilter&          pathFilter,
                                       const nogdb::ClassFilter&         classFilter
                                      )
receive only one RecordDescriptor

**Comment by pj4dev** [comment]
The implementation for this feature request can be found in https://github.com/nogdb/libnogdb/pull/57.

**Comment by pj4dev** [comment]
This is already available in nogdb v1.1.0. This issue can be closed.
